### PR TITLE
Sec struct

### PR DESCRIPTION
**Pull request by sreisser**
Hi,
this uses output of ANNOTATE to minimize and draw secondary structures:
1) minimize on dotbracket, draw dotbracket
2) minimize on stack+pair, draw stack+pair
3) minimize on dotbracket, draw stack+pair
For trajectories (multiple frames), interactions are color-coded by population.
It's also possible to use VARNA or RNAstructure svg as template positions for the residues. 

I changed the output in ANNOTATE to read residue IDs and nucleotides from the sequence (added an extra line).

Code might still a bit messy but should be working now.
It draws most of the structures I tried fine, including pseudoknots, however can get messy with large structures with many interactions. Let me know if you have suggestions (also esthetic ones) or have a specific molecule that's not working.

Cheers, have a good weekend
Sabine

### CODE REVIEW

**Comment by sbottaro** [comment]
Hi @sreisser, thanks! this looks great. It seems that RMSD tests fail - is it because you changed to backbone-only RMSD? Should we add a flag so that the user can choose whether to use BB-only or heavy-atoms?

**Comment by GiovanniBussi** [comment]
@sreisser is it possible to add a regtest for this?

**Comment by sreisser** [comment]
Hi @sbottaro,

yes sorry I forgot to reverse that. Yes I think it would be useful to have
an option for BB-only, to be able to better compare different sequences.

Cheers
Sabine

2018-05-19 14:47 GMT+02:00 Sandro <notifications@github.com>:

**Comment by sbottaro** [comment]
Yes, that's a good idea. I open a new issue now.

**Pull request merged**
