### PR TITLE
Attempt to install script correctly

### PR DESCRIPTION
**Pull request by GiovanniBussi**
@sbottaro @wouterboomsma 

I tried to make the baRNAba script installable by pip. Namely:
- I moved `bin/baRNAba.py` to `barnaba/__main__.py`
- I added a symlink from `bin/baRNAba.py` to `barnaba/__main__.py`
- I changed `setup.py` specifying `barnaba.__main__:main` as an entry point.

Can you check if what I did is right and in case merge it? Thanks!

Giovanni

### CODE REVIEW

**Comment by sbottaro** [comment]
Hi, @wouterboomsma is currently working on pip installation

**Comment by GiovanniBussi** [comment]
Great! Meanwhile, I just report that with this change I am able to install barnaba within MacPorts. After `port install py36-barnaba` I have an executable named `/opt/local/bin/baRNAba-3.6` that works.

**Comment by wouterboomsma** [comment]
This looks like the right way to do it. But what was the reason for renaming the file from `baRNAba.py` to `__main__.py`?

**Comment by GiovanniBussi** [comment]
@wouterboomsma probably it's not necessary... please, just forget the way I did it and do it in the correct way :-)

Giovanni

**Comment by GiovanniBussi** [comment]
Done in 34e2ac84c91dc1fc161ef2464b8c702aa673c931

**Pull request closed without merging**
